### ISSUE TITLE
pip install - missing utils forlder

### ISSUE THREAD

**Issue by fritz-k** [theatlantic/django-cropduster#31]
When installed with pip install django-cropduster, I get an "ImportError: No module named 'cropduster.utils'" because the utils forlder wasn't installed by pip.
Edit: I'm using python 3.4 and pip 6.0.8 if that makes a difference

**Comment by fdintino** [comment]
Thank you for pointing this out! This must have been broken for quite a while. The latest version on PyPI (4.8.5) should fix this issue.
