### ISSUE TITLE
Extra db thumb entries being created when cropping images after upload.

### ISSUE THREAD

**Issue by cgreinke** [theatlantic/django-cropduster#41]
I have a test model defined similarly to the example in the documentation (just with one `CropDusterField`):
```python
class Test(models.Model):
    image = CropDusterField(
        upload_to=u"img/upload",
        sizes=[
            Size("main", w=1024, h=768, label="Main", auto=[
                Size("square", w=1000, h=1000),
                Size("main@2x", w=2048, h=1536, required=False),
            ]),
            Size("thumb", w=400, label="Thumbnail"),
            Size("freeform", label="Free-form")
        ],
    )
```
When in the "Upload, Crop, and Generate Thumbnails" popup, after clicking "Upload Image" in the admin, each crop step adds some extra rows to the `cropduster4_thumb` table. So after all of the crops have taken place, there are 13 rows in the table. I would figure there to be only 5 rows (one for each size defined). These extra 8 rows are left behind even after deleting the image from the change page in the admin.

My current (possibly incorrect) theory is that it has something to do with the value for `thumbs-INITIAL_FORMS` value in the management form not being updated with each step of cropping.

Can you guys reproduce the problem?

**Comment by fdintino** [comment]
Wow, great catch. Not only was I able to reproduce the problem, your theory was absolutely correct. Thanks!
