### ISSUE TITLE
on_delete and Django 1.9

### ISSUE THREAD

**Issue by shacker** [theatlantic/django-cropduster#44]
Using Django 1.9rc1, set up exactly as shown in the cropduster tutorial, I get this on startup:

`TypeError: __init__() missing 1 required positional argument: 'on_delete'`

(let me know if you want more of the traceback)

**Comment by fdintino** [comment]
Support for django 1.9 is forthcoming, probably next week.

**Comment by fdintino** [comment]
Sorry for the delay in getting this fix up. Can you check that it works now? (If you already have it installed you'll need to update django-generic-plus as well).

**Comment by shacker** [comment]
Ah, I moved on to another solution, so am not able to test. Thanks for the fix though!
