### ISSUE TITLE
Any plans to support Django 1.10?

### ISSUE THREAD

**Issue by kiwiheretic** [theatlantic/django-cropduster#50]

**Comment by fdintino** [comment]
Can you test out the [django-110](https://github.com/theatlantic/django-cropduster/tree/django-110) branch?

**Comment by fdintino** [comment]
I merged django 1.10+ compatibility into master, and all of the unit tests pass. Let me know if you run into any issues.

**Comment by kiwiheretic** [comment]
Thank you.
